# Generated by Django 4.1.7 on 2023-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(default='Firstname', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='middlename',
            field=models.TextField(default='Middlename', max_length=20),
        ),
    ]
