# Generated by Django 4.1.7 on 2023-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_firstname_profile_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(default='Lastname', max_length=20),
        ),
    ]
