# Generated by Django 4.1.7 on 2023-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area_or',
            field=models.TextField(default='Area'),
        ),
    ]
