# Generated by Django 4.1.7 on 2023-03-13 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.TextField(default='Middlename', max_length=20)),
                ('lastname', models.TextField(default='Lastname', max_length=20)),
                ('email', models.EmailField(default='user@email.com', max_length=254)),
                ('phone_number', models.IntegerField(default='0000000000')),
                ('id_number', models.CharField(default='GHA-#########-#', max_length=20)),
                ('age', models.IntegerField(default='10')),
                ('area_or', models.TextField(default='Area')),
                ('firstname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
