# Generated by Django 4.1.7 on 2023-03-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
        migrations.AddField(
            model_name='details',
            name='town',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='details',
            name='firstname',
            field=models.TextField(default='Firstnaem', max_length=20),
        ),
    ]
