# Generated by Django 4.1.7 on 2023-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_details_age_details_town_details_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='firstname',
            field=models.TextField(default='Firstname', max_length=20),
        ),
    ]
