# Generated by Django 4.1.7 on 2023-03-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_details_firstname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
