# Generated by Django 4.1.7 on 2023-03-14 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_Status',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending#', max_length=10)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
