# Generated by Django 4.1.7 on 2023-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_status',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
