# Generated by Django 4.1.7 on 2023-03-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_donor_status_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(default='Firstname', max_length=20)),
                ('middlename', models.TextField(default='Middlename', max_length=20)),
                ('lastname', models.TextField(default='Lastname', max_length=20)),
                ('email', models.EmailField(default='user@email.com', max_length=254)),
                ('phone_number', models.IntegerField(default='')),
                ('area_or', models.TextField(default='Area')),
                ('town', models.TextField(default='')),
                ('donor', models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
