# Generated by Django 4.1.7 on 2023-03-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_donor_id_delete_donor_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
