# Generated by Django 4.1.7 on 2023-03-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_donor_remove_profile_area_or'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_card',
            field=models.CharField(default='NBS/20/##########/', max_length=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='hospital',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_of_patient',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(default='##########', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='ward',
            field=models.CharField(default='Ward #', max_length=10),
        ),
    ]
