# Generated by Django 4.1.7 on 2023-03-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_donor_donor_card_donor_donor_number_donor_hospital_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
