# Generated by Django 4.1.7 on 2023-04-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_donor_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='region',
        ),
    ]
