# Generated by Django 4.1.7 on 2023-04-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='region',
        ),
    ]
