# Generated by Django 4.1.7 on 2023-04-17 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_remove_donor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='region',
            field=models.CharField(choices=[('ahafo', 'Ahafo Region'), ('ashanti', 'Ashanti Region'), ('bono', 'Bono East Region'), ('brong', 'Brong Ahafo Region'), ('central', 'Central Region'), ('eastern', 'Eastern Region'), ('greater', 'Greater Accra Region'), ('north east', 'North East Region'), ('northern', 'Northern Region'), ('oti', 'Oti Region'), ('savannah', 'Savannah Region'), ('upper east', 'Upper East Region'), ('upper west', 'Upper West Region'), ('western', 'Western Region'), ('western north', 'Western North Region'), ('volta', 'Volta Region')], default='ahafo', max_length=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
